[2022-03-18 04:53:10,928] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-12T04:00:00+00:00 [queued]>
[2022-03-18 04:53:11,170] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-12T04:00:00+00:00 [queued]>
[2022-03-18 04:53:11,178] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:53:11,182] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-03-18 04:53:11,185] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:53:11,470] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2010-03-12 04:00:00+00:00
[2022-03-18 04:53:13,302] {standard_task_runner.py:52} INFO - Started process 225 to run task
[2022-03-18 04:53:15,816] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2010-03-12T04:00:00+00:00', '--job-id', '6325', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmphuwgcyli', '--error-file', '/tmp/tmpp7kmf_b5']
[2022-03-18 04:53:17,889] {standard_task_runner.py:77} INFO - Job 6325: Subtask get_pbp_data
