[2022-03-18 15:27:34,858] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2011-06-30T04:00:00+00:00 [queued]>
[2022-03-18 15:27:34,953] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2011-06-30T04:00:00+00:00 [queued]>
[2022-03-18 15:27:34,959] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 15:27:34,963] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-03-18 15:27:34,967] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 15:27:35,030] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2011-06-30 04:00:00+00:00
[2022-03-18 15:27:35,060] {standard_task_runner.py:52} INFO - Started process 103 to run task
[2022-03-18 15:27:35,099] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2011-06-30T04:00:00+00:00', '--job-id', '6520', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmpzqtmg1la', '--error-file', '/tmp/tmphfuy5ew9']
[2022-03-18 15:27:35,111] {standard_task_runner.py:77} INFO - Job 6520: Subtask get_pbp_data
[2022-03-18 15:27:35,547] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2011-06-30T04:00:00+00:00 [running]> on host 64466ce74801
[2022-03-18 15:27:35,868] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_bucket_ingestion_dag
AIRFLOW_CTX_TASK_ID=get_pbp_data
AIRFLOW_CTX_EXECUTION_DATE=2011-06-30T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2011-06-30T04:00:00+00:00
[2022-03-18 15:28:05,620] {python.py:175} INFO - Done. Returned value was: None
[2022-03-18 15:28:05,763] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_bucket_ingestion_dag, task_id=get_pbp_data, execution_date=20110630T040000, start_date=20220318T152734, end_date=20220318T152805
[2022-03-18 15:28:05,843] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
